---
title: "Overzicht melkcontrole"
output: html_document
---

```{r setup, include=FALSE,echo = FALSE}
taal <- "nl"
## taalsleutels
source('taalsleutels.R')
knitr::opts_chunk$set(echo = TRUE)
library(RODBC)
library(RPostgres)
library(stringr)
library(dotenv)
library(reshape2)
library(kableExtra)

load_dot_env()

for(VAR in c(
  'PG_HOST',
  'PG_DB',
  'PG_USER',
  'PG_PWD')){
	assign(VAR, Sys.getenv(VAR))
	if(get(VAR) == '') stop(paste0('Missing ', VAR))
}

if(!exists('pgdb')){
	pgdb <- dbConnect(Postgres(), host = PG_HOST, dbname = PG_DB, user = PG_USER, pass = PG_PWD)
	quer_pg <- function(...) dbGetQuery(pgdb, str_glue(paste0(...)))
	quer_str <- function(...)str_glue(paste0(...))
	pgex <- function(...) dbExecute(pgdb, paste0(...))
}

meanle <- function(x,ndec = 2){
    x <- x[!is.na(x)]
    paste(format(round(mean(x),ndec),nsmall = ndec)," (",length(x),")",sep = "")
}
klant <- "milsana"
kid <- quer_pg("select id from farms where name = '",klant,"'")

dats <- quer_pg("select distinct(mc.date_time)
                from milk_controls mc 
                where mc.farms_id = ",kid)$date_time
maxd <- max(dats)
mind <- maxd-months(18)
dats <- quer_pg("select distinct(mc.date_time)
                from milk_controls mc
                where mc.farms_id = ",kid,
                "and date_time >= '",mind,"'")$date_time

dd <- paste("('",paste(dats,collapse = "','"),"')\n",sep = "")

## selecteer alle gegevens van dieren die aanwezig waren op de dagen van controle
pgex("drop table if exists temp_tab_ids")
pgex("select distinct farms_id,pedigree_id,nlact
                    into temp_tab_ids
                    from views.view_mc 
                    where farms_id = ",kid,
                    "and date_time > '",mind,"'")
## haal die op
mprdata <- quer_pg("select mc.*
              from views.view_mc mc
              inner join temp_tab_ids tt
              using(farms_id,pedigree_id,nlact)
              where mc.production > 0
              order by farms_id,pedigree_id,date_time")
mpd <- mprdata

mprdata <- mpd
mprdata$dil <- as.numeric(gsub("[[:space:]]days","",mprdata$dil))
mprdata$double <- FALSE

## mprdata met alle lakts
m2 <- mprdata
m2$nlact <- -1
m2$double <- TRUE

## mprdata met alle dils
m3 <- mprdata
m3$dil <- -1
m3$double <- TRUE

## mprdata met alle dils en lakts
m4 <- mprdata
m4$dil <- -1
m4$nlact <- -1
m4$double <- TRUE
mprdata <- rbind(rbind(rbind(mprdata,m2),m3),m4)

mprdata$nlactcat <- factor(with(mprdata,ifelse(nlact>2,3,nlact)))
levels(mprdata$nlactcat) <- sleutels$nlactcat[[taal]]
mprdata$dilcat <- factor(cut(mprdata$dil,breaks = c(-10,0,30,60,200,max(mprdata$dil,na.rm = T))))
levels(mprdata$dilcat) <- sleutels$dilcat[[taal]]

```

```{r snelzicht, echo = FALSE,results='character'}
sn <- matrix(unlist(by(mprdata[mprdata$date_time>mind&!mprdata$double,],
                       mprdata$date_time[mprdata$date_time>mind&!mprdata$double],function(tt){
                       with(tt,c(n = as.character(length(pedigree_id)),
                                 pv = as.character(round(mean(nlact == 1)*100,0)),
                                 dil = as.character(round(mean(dil,na.rm = T))),
                                 prod = as.character(round(mean(production,na.rm = T),2)),
                                 isk = as.character(round(mean(isk,na.rm = T),2)),
                                 fat = as.character(round(sum(fat_pct*production,na.rm = T)/sum(ifelse(!is.na(fat_pct),production,0),na.rm = T),2)),
                                 protein = as.character(round(sum(protein_pct*production,na.rm = T)/sum(ifelse(!is.na(protein_pct),production,0),na.rm = T),2)),
                                 cells = as.character(round(sum(cells*production,na.rm = T)/sum(ifelse(!is.na(cells),production,0),na.rm = T),0))))})),
             byrow = T,ncol = 8)
rownames(sn) <- unique(as.character(mprdata$date_time[mprdata$date_time>mind]))
colnames(sn) <- sleutels$tabsnelzicht[[taal]]
sn %>%
  kbl(caption = sleutels$cptsnelzicht[[taal]]) %>%
  kable_styling(fixed_thead = T) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"))
```

```{r productie,echo = FALSE,results = 'character'}
tp <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(production,list(nlactcat,dilcat,date_time),meanle)))
tp <- dcast(tp,Var1+Var2 ~Var3)
colnames(tp)[2] <- ""
tp <- tp[,c(1:2,2 + order(colnames(tp)[-(1:2)],decreasing = T))]
tp[,-c(1)] %>%
  kbl(caption = sleutels$cptproduction[[taal]]) %>%
  kable_styling(fixed_thead = T) %>%
  kable_styling(bootstrap_options = c("striped", "hover",  "responsive")) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```

```{r vet,echo = FALSE,results = 'character'}
tf <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(fat_pct),list(nlactcat,dilcat,date_time),function(i)
        round(sum(fat_pct[i]*production[i])/sum(production[i]),2))))
tf <- dcast(tf,Var1+Var2 ~Var3)
colnames(tf)[2] <- ""
tf <- tf[,c(1:2,2 + order(colnames(tf)[-(1:2)],decreasing = T))]
tf[,-c(1)] %>%
  kbl(caption = sleutels$cptfat[[taal]]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "responsive")) %>%
  kable_styling(fixed_thead = T) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```

```{r protein,echo =FALSE,results = 'character'}
tprot <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(fat_pct),list(nlactcat,dilcat,date_time),function(i)
        round(sum(protein_pct[i]*production[i])/sum(production[i]),2))))
tprot <- dcast(tprot,Var1+Var2 ~Var3)
tprot <- tprot[,c(1:2,2 + order(colnames(tprot)[-(1:2)],decreasing = T))]
colnames(tprot)[2] <- ""
tprot[,-c(1)] %>%
  kbl(caption = sleutels$cptprotein[[taal]]) %>%
  kable_styling(fixed_thead = T) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```

```{r lactose,echo = FALSE,results = 'character'}
tlact <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(lact_pct),list(nlactcat,dilcat,date_time),function(i)
        round(sum(lact_pct[i]*production[i])/sum(production[i]),2))))
tlact <- dcast(tlact,Var1+Var2 ~Var3)
tlact <- tlact[,c(1:2,2 + order(colnames(tlact)[-(1:2)],decreasing = T))]
colnames(tlact)[2] <- ""
tlact[,-c(1)] %>%
  kbl(caption = sleutels$cptlact[[taal]]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  kable_styling(fixed_thead = T) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```

```{r ketose,echo = FALSE,results = 'character'}
tketo <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(pedigree_id),list(nlactcat,dilcat,date_time),function(i)
        round(mean((fat_pct[i] - protein_pct[i])>1.5 & protein_pct[i]<3.25)*100,1))))
tketo <- dcast(tketo,Var1+Var2 ~Var3)
tketo <- tketo[,c(1:2,2 + order(colnames(tketo)[-(1:2)],decreasing = T))]
colnames(tketo)[2] <- ""
tketo[,-c(1)] %>%
  kbl(caption = sleutels$cptketose[[taal]]) %>%
  kable_styling(fixed_thead = T) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```

```{r acidosis,echo=FALSE,results = 'character'}
tacid <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(pedigree_id),list(nlactcat,dilcat,date_time),function(i)
        round(mean((protein_pct[i]>fat_pct[i]) & fat_pct[i]<4)*100,1))))
tacid <- dcast(tacid,Var1+Var2 ~Var3)
tacid <- tacid[,c(1:2,2 + order(colnames(tacid)[-(1:2)],decreasing = T))]
colnames(tacid)[2] <- ""
tacid[,-c(1)] %>%
  kbl(caption = sleutels$cptacidose[[taal]]) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  kable_styling(fixed_thead = T) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```

```{r scc,echo = FALSE,results = 'character'}
tcel <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(cells),list(nlactcat,dilcat,date_time),function(i)
        round(sum(cells[i]*production[i])/sum(production[i]),0))))
tcel<- dcast(tcel,Var1+Var2 ~Var3)
tcel <- tcel[,c(1:2,2 + order(colnames(tcel)[-(1:2)],decreasing = T))]
colnames(tcel)[2] <- ""
tcel[,-c(1)] %>%
  kbl(caption = sleutels$cptscc[[taal]]) %>%
  kable_styling(fixed_thead = T) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```



```{r scchoog,echo = FALSE,results = 'character'}
tchoog <- melt(with(mprdata[mprdata$date_time>mind,],
      tapply(1:length(cells),list(nlactcat,dilcat,date_time),function(i)
        round(mean(ifelse(nlact[i]==1,cells>150,cells>200))*100,0))))
tchoog<- dcast(tchoog,Var1+Var2 ~Var3)
tchoog <- tchoog[,c(1:2,2 + order(colnames(tchoog)[-(1:2)],decreasing = T))]
colnames(tchoog)[2] <- ""
tchoog[,-c(1)] %>%
  kbl(caption = sleutels$cptchoog[[taal]]) %>%
  kable_styling(fixed_thead = T) %>%
  kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive")) %>%
  pack_rows(sleutels$nlactcat[[taal]][1],1,5) %>%
  pack_rows(sleutels$nlactcat[[taal]][2],6,10) %>%
  pack_rows(sleutels$nlactcat[[taal]][3],11,15) %>%
  pack_rows(sleutels$nlactcat[[taal]][4],16,20) %>%
  scroll_box(width = "1000px", height = "800px")
```






